# https://github.com/paritytech/parity/wiki/Configuring-Parity
[parity]
chain = "chain.json"
[mining]
reseal_min_period = 0
reseal_max_period = 0
reseal_on_uncle = true
force_sealing = true
[rpc]
cors = []
hosts = ["all"]
[websockets]
origins = ["localhost:8080"]
[network]
min_peers = 0
max_peers = 0
