# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.1
      - image: circleci/mongo:latest
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # - run: sudo apt-get update
      # - run: sudo apt-get install openssl libssl-dev libudev-dev
      - run: wget https://www.openssl.org/source/openssl-1.1.0.tar.gz
      - run: tar xzvf openssl-1.1.0.tar.gz && cd openssl-1.1.0
      - run: cd openssl-1.1.0 && ./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)' && make && sudo make install
      - run: openssl version
      - run: ldd /usr/local/bin/openssl
      - run: which libssl
      - run: sudo apt-get install lsb-release
      - run: bash <(curl https://get.parity.io -Lk)
      - run: npm install
      - run: npm install web3@1.0.0-beta.28 --save
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: run parity in background
          command: npm run parity
          background: true
      - run: npm run lint
      - run: npm test
