# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: leeaandrob/paratii-db:0.0.1
      - image: circleci/mongo:latest
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies

      - run: npm install
      - run: npm install web3@1.0.0-beta.28 --save
      - run: npm -v
      - run: node -v
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: run parity in background
          command: npm run parity
          background: true
      - run: npm run lint
      - run: npm test
