FROM node:8.9.2
WORKDIR /root/parity
COPY parity-config-docker.toml /root/parity/
COPY chain.json /root/parity/
RUN apt-get install -y wget
RUN wget -q https://parity-downloads-mirror.parity.io/v1.9.0/x86_64-unknown-linux-gnu/parity_1.9.0_amd64.deb && dpkg -i parity_1.9.0_amd64.deb
